openapi: 3.0.2
paths:
  /status:
    get:
      description: Should return OK
      summary: Health status endpoint
      tags: []
      parameters: []
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type:
                  - string
                enum:
                  - OK
  /signals:
    post:
      description: Insert a signal
      summary: Push Signal
      tags: []
      parameters:
        - name: authorization
          in: header
          required: true
          schema:
            type:
              - string
      requestBody:
        description: Body
        content:
          application/json:
            schema:
              type:
                - object
              properties:
                signalType:
                  type:
                    - string
                  enum:
                    - CREATE
                    - UPDATE
                    - DELETE
                    - SEEDUPDATE
                objectId:
                  type:
                    - string
                eserviceId:
                  type:
                    - string
                signalId:
                  type:
                    - number
                objectType:
                  type:
                    - string
              required:
                - signalType
                - objectId
                - eserviceId
                - signalId
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  signalId:
                    type:
                      - number
                required:
                  - signalId
        '400':
          description: '400'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  type:
                    type:
                      - string
                  status:
                    type:
                      - number
                  title:
                    type:
                      - string
                  correlationId:
                    type:
                      - string
                      - 'null'
                  detail:
                    type:
                      - string
                  errors:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        code:
                          type:
                            - string
                        detail:
                          type:
                            - string
                      required:
                        - code
                        - detail
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
        '401':
          description: '401'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  type:
                    type:
                      - string
                  status:
                    type:
                      - number
                  title:
                    type:
                      - string
                  correlationId:
                    type:
                      - string
                      - 'null'
                  detail:
                    type:
                      - string
                  errors:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        code:
                          type:
                            - string
                        detail:
                          type:
                            - string
                      required:
                        - code
                        - detail
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
        '403':
          description: '403'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  type:
                    type:
                      - string
                  status:
                    type:
                      - number
                  title:
                    type:
                      - string
                  correlationId:
                    type:
                      - string
                      - 'null'
                  detail:
                    type:
                      - string
                  errors:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        code:
                          type:
                            - string
                        detail:
                          type:
                            - string
                      required:
                        - code
                        - detail
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
        '500':
          description: '500'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  type:
                    type:
                      - string
                  status:
                    type:
                      - number
                  title:
                    type:
                      - string
                  correlationId:
                    type:
                      - string
                      - 'null'
                  detail:
                    type:
                      - string
                  errors:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        code:
                          type:
                            - string
                        detail:
                          type:
                            - string
                      required:
                        - code
                        - detail
                required:
                  - type
                  - status
                  - title
                  - detail
                  - errors
  /signals/{eserviceId}:
    get:
      description: Retrieve a list o signals on a specific eservice starting from signalId
      summary: Get a list of signals
      tags: []
      parameters:
        - name: eserviceId
          in: path
          required: true
          schema:
            type:
              - string
        - name: authorization
          in: header
          required: true
          schema:
            type:
              - string
        - name: signalId
          in: query
          schema:
            default: 0
            type:
              - number
            minimum: 0
        - name: size
          in: query
          schema:
            default: 10
            type:
              - number
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  signals:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        signalType:
                          type:
                            - string
                          enum:
                            - CREATE
                            - UPDATE
                            - DELETE
                            - SEEDUPDATE
                        objectId:
                          type:
                            - string
                        eserviceId:
                          type:
                            - string
                        signalId:
                          type:
                            - number
                        objectType:
                          type:
                            - string
                      required:
                        - signalType
                        - objectId
                        - eserviceId
                        - signalId
                  lastSignalId:
                    type:
                      - number
                      - 'null'
                required:
                  - signals
        '206':
          description: '206'
          content:
            application/json:
              schema:
                type:
                  - object
                properties:
                  signals:
                    type:
                      - array
                    items:
                      type:
                        - object
                      properties:
                        signalType:
                          type:
                            - string
                          enum:
                            - CREATE
                            - UPDATE
                            - DELETE
                            - SEEDUPDATE
                        objectId:
                          type:
                            - string
                        eserviceId:
                          type:
                            - string
                        signalId:
                          type:
                            - number
                        objectType:
                          type:
                            - string
                      required:
                        - signalType
                        - objectId
                        - eserviceId
                        - signalId
                  lastSignalId:
                    type:
                      - number
                      - 'null'
                required:
                  - signals
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        A bearer token in the format of a JWS and conformed to the
        specifications included in
        [RFC8725](https://tools.ietf.org/html/RFC8725).
info:
  title: Pull-signal
  version: 0.1.1
