openapi: 3.0.0
info:
  version: 1.0.0
  title: My API test
  description: This is the API
servers:
  - url: v1
components:
  schemas:
    SignalPushResponse:
      type: object
      properties:
        signalId:
          type: number
      required:
        - signalId
    Problem:
      type: object
      properties:
        type:
          type: string
        status:
          type: number
        title:
          type: string
        correlationId:
          type: string
          nullable: true
        detail:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              code:
                type: string
              detail:
                type: string
            required:
              - code
              - detail
      required:
        - type
        - status
        - title
        - detail
        - errors
    Signal:
      type: object
      properties:
        signals:
          type: array
          items:
            type: object
            properties:
              signalType:
                type: string
                enum: &ref_0
                  - CREATE
                  - UPDATE
                  - DELETE
                  - SEEDUPDATE
              objectId:
                type: string
              eserviceId:
                type: string
              signalId:
                type: number
              objectType:
                type: string
            required:
              - signalType
              - objectId
              - eserviceId
              - signalId
              - objectType
        lastSignalId:
          type: number
          nullable: true
      required:
        - signals
  parameters: {}
paths:
  /status:
    GET:
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                type: string
                enum:
                  - OK
  /signals:
    POST:
      parameters:
        - schema:
            type: string
          required: true
          name: authorization
          in: header
      requestBody:
        description: ''
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                signalType:
                  type: string
                  enum: *ref_0
                objectId:
                  type: string
                eserviceId:
                  type: string
                signalId:
                  type: number
                objectType:
                  type: string
              required:
                - signalType
                - objectId
                - eserviceId
                - signalId
                - objectType
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignalPushResponse'
        '400':
          description: '400'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '401':
          description: '401'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '403':
          description: '403'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '500':
          description: '500'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
  /signals/{eserviceId}:
    GET:
      parameters:
        - schema:
            type: string
          required: true
          name: eserviceId
          in: path
        - schema:
            type: number
            nullable: true
            minimum: 0
            default: 0
          required: false
          name: signalId
          in: query
        - schema:
            type: number
            minimum: 1
            maximum: 100
            default: 10
          required: false
          name: size
          in: query
        - schema:
            type: string
          required: true
          name: authorization
          in: header
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Signal'
        '206':
          description: '206'
          content:
            application/json:
              schema:
                type: object
                properties:
                  signals:
                    type: array
                    items:
                      type: object
                      properties:
                        signalType:
                          type: string
                          enum: *ref_0
                        objectId:
                          type: string
                        eserviceId:
                          type: string
                        signalId:
                          type: number
                        objectType:
                          type: string
                      required:
                        - signalType
                        - objectId
                        - eserviceId
                        - signalId
                        - objectType
                  lastSignalId:
                    type: number
                    nullable: true
                required:
                  - signals
